# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a2c920f8e834d3f84ead83e9161b126d"
application_url = "https://capacity-phases-favour-usgs.trycloudflare.com"
embedded = true
name = "Ai-Agent"
handle = "ai-agent-15"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = false

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://capacity-phases-favour-usgs.trycloudflare.com/auth/callback",
  "https://capacity-phases-favour-usgs.trycloudflare.com/auth/shopify/callback",
  "https://capacity-phases-favour-usgs.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
